### ISSUE TITLE
Create experimental POST/PATCH (create and update) APIs for CF Apps and Packages

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-crd-explorations#4]
## Background

Using the CRDs we created in #1, let's spike out a couple of custom resource-backed API endpoints that are used by the `cf push` workflow. In this story we'll explore what *creating* and *updating* App CRs via a rest API looks like.

Creating and updating Apps is interesting since it ties nicely with TME-113 and can give an initial demo-able experience. We should also explore what creating a child resource of an App looks like and how best to model that relationship with CRDs (labels? spec properties? ownerReferences? some combination of several of these?). A good candidate for this would be the `Package` CR via `POST /v3/packages`.

Questions we'd like to answer:
 * What is necessary to communicate with the Kubernetes API
 * How we can model relationships between custom resources in a way that makes sense with the CF API
 * CF API design has a lot of assumptions around using a relational database available to provide atomicity.

## Deliverable
 * You should be able to curl the `POST /v3/apps`, `PATCH /v3/apps/:guid`, and `POST /v3/packages` endpoints and see minimal differences from what you'd see on CF for VMs/cf-for-k8s
 * We should then be able to use the GET endpoints we made in #2 to view these apps
 * Keep a journal of what was difficult, what was easy, etc.

----

## Dev Notes
 * Refer to [this Miro board](https://miro.com/app/board/o9J_lFiI8CU=/) for inspiration.
 * v3 API docs: https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#create-an-app
 * This only concerns updating Apps and Packages. We are not uploading any bits or anything -- feel free to use a pre-uploaded source image on the Package.

### Dev Provided Acceptance Steps:
_**Fill me in**_

**Comment by matt-royal** [comment]
As part of this work we have to decide how to handle the envSecretName field. Here are our options:
1. Lazily create the secret to hold an apps environment variables when they are first added. Before that there is no secret
2. Create a secret for the app when it is first created, but that secret would have no environment variables set until the user makes the correct API calls to do so. This may never happen.

@akrishna90 and I think it's wasteful to create blank secrets, so we prefer option 1. This requires the following change:
- [ ] Change the ProcessController so it skips looking up the environment variables when `envSecretName` is `""`

**Comment by matt-royal** [comment]
As per [this conversation](https://vmware.slack.com/archives/G01EM3JJ79D/p1624313335116700) with @tcdowney we are going to ignore the metadata.labels information in the v3 API for now. Eirini doesn't seem to support them and it was an intentional decision in cf-for-k8s not to propagate them into k8s for security reasons. Tim will spin off a separate story to decide how to handle them.

**Comment by tcdowney** [comment]
@matt-royal here's the exploratory story that captures some of that context: https://github.com/cloudfoundry/cf-crd-explorations/issues/9

**Comment by matt-royal** [comment]
We spent a few minutes digging into how cf-for-k8s handles the case when the lifecycle buildpacks and stack are omitted. For the stack, we seem to ignore it in all cases and just use the stack from the default CF kpack builder. For the buildpacks, if none are specified then we use that same default builder, which includes all buildpacks. If the user specifies buildpacks, then we ensure that a builder with those buildpacks exists (or we create one), then we use that builder to stage.

**Comment by tcdowney** [comment]
## Acceptance

### 🚨  **Results** 🚨 
**Moving this story back to "to-do" for the following issues:**

* Creating an App should not require optional fields (like `lifecycle`). Our param requirements should match the CF API: https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#create-an-app
* Creating a Package did not put the package in the same `namespace` as its App
* Creating a Package before an App should fail with a `422` (it currently allows it to be created)
* Updating an App should use a `PATCH` request instead of a `PUT`
* Updating an App that doesn't exist should fail more gracefully (`404` instead of panic)

---

### Scenario: Happy Path 😊
1. Creating an App
Tried following the README, but it only documented how to do a `PUT`. Went to the [V3 API docs for creating an app](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#create-an-app) and tried the following:

```
curl "http://localhost:81/v3/apps" \
  -X POST \
  -d '{
    "name": "my-app",
    "relationships": {
      "space": {
        "data": {
          "guid": "cf-workloads"
        }
      }
    }
  }'
```

This failed to create the app and the controller had errors like:
```
error creating App object: {{ } {d6269582-31da-403c-ab5e-2db1fbd67636  cf-workloads    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []} {my-app STOPPED kpack {{[] }}  {  }} {}}
```

I think added lifecycle data (which is not required by the CF for VMs API) and it succeeded.
```
curl "http://localhost:81/v3/apps" \
  -X POST \
  -d '{
    "name": "my-app",
    "lifecycle":{"type":"kpack","data":{"buildpacks":["java_buildpack","ruby"],"stack":"cflinuxfs3"}},
    "relationships": {
      "space": {
        "data": {
          "guid": "cf-workloads"
        }
      }
    }
  }'
```

This created an app named `5b1da1ce-dd6a-4d92-8586-619932c3ed1b` in the namespace `cf-workloads`. 

2.  Creating the Package
```
curl "http://localhost:81/v3/packages" \
  -X POST \
  -d '{"type":"docker","relationships":{"app":{"data":{"guid":"5b1da1ce-dd6a-4d92-8586-619932c3ed1b"}}},"data":{"image":"registry/your-image:latest","username":"dockerusername","password":"dockerpassword"}}'
```

This created a Package named `d32cbcbe-97d5-4653-bb34-09db55ee59b0` in the `default` namespace. It should have been created in the same namespace as the App (`cf-workloads`).

---

### Scenario: Creating Package before the App
1. Created a Package
```
curl "http://localhost:81/v3/packages" \
  -X POST \
  -d '{"type":"docker","relationships":{"app":{"data":{"guid":"9f924342-472a-43a1-9db9-54beba5401e2"}}},"data":{"image":"registry/your-image:latest","username":"dockerusername","password":"dockerpassword"}}'
  ```

The Package was successfully created even though the App did not exist. Since a Package must be tied to an App and it discovers its Space (`namespace` on K8s) via the App it should [have errored with a `422`](https://github.com/cloudfoundry/cloud_controller_ng/blob/5787b935f80f4bdc48b236cca68d0595928dc944/app/controllers/v3/packages_controller.rb#L150).

---

### Scenario: Updating an App that **does** exist
1. Updated an App that had it's buildpacks set to `java` and `ruby` to use `java` and `python`
```
curl "http://localhost:81/v3/apps/5b1da1ce-dd6a-4d92-8586-619932c3ed1b" \
  -X PUT \
  -d '{"name":"my-app","lifecycle":{"type":"kpack","data":{"buildpacks":["java_buildpack","python"],"stack":"cflinuxfs3"}}}'
```

This worked! We then played around with removing keys and saw when we removed lifecycle it errored out.

```
curl "http://localhost:81/v3/apps/5b1da1ce-dd6a-4d92-8586-619932c3ed1b" \
  -X PUT \
  -d '{"name":"my-app"}'
```

```
error updating App object: {{App apps.cloudfoundry.org/v1alpha1} {5b1da1ce-dd6a-4d92-8586-619932c3ed1b  cf-workloads  5058d68e-77fe-4f25-8b5b-186ecafec921 1231728 2 2021-07-02 10:12:40 -0700 PDT <nil> <nil> map[] map[] [] []  [{main Update apps.cloudfoundry.org/v1alpha1 2021-07-02 10:12:40 -0700 PDT FieldsV1 {"f:spec":{".":{},"f:currentDropletRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{}},"f:envSecretName":{},"f:lifecycle":{".":{},"f:data":{".":{},"f:buildpacks":{},"f:stack":{}}},"f:name":{},"f:state":{},"f:type":{}},"f:status":{}}}]} {my-app STOPPED kpack {{[] }}  {  }} {}}
```

---

### Scenario: Updating an App that **doesn't** exist
1. Updated an App with a guid that doesn't exist
```
curl "http://localhost:81/v3/apps/9f924342-472a-43a1-9db9-54beba5401e2" \
  -X PUT \
  -d '{"name":"my-app","lifecycle":{"type":"kpack","data":{"buildpacks":["java_buildpack","ruby"],"stack":"cflinuxfs3"}}}'
```

Got back the following error:
```
2021/07/02 10:04:11 http: panic serving [::1]:61506: runtime error: index out of range [0] with length 0
goroutine 459 [running]:
net/http.(*conn).serve.func1(0xc00045ca00)
	/usr/local/Cellar/go/1.16.3/libexec/src/net/http/server.go:1824 +0x153
panic(0x2351dc0, 0xc000460330)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:971 +0x499
cloudfoundry.org/cf-crd-explorations/cfshim/handlers.(*AppHandler).UpdateAppsHandler(0xc00049f7a0, 0x2644e50, 0xc0007ca380, 0xc000124c00)
	/Users/tdowney/workspace/cf-crd-explorations/cfshim/handlers/app_handler.go:299 +0x705
net/http.HandlerFunc.ServeHTTP(0xc000418140, 0x2644e50, 0xc0007ca380, 0xc000124c00)
	/usr/local/Cellar/go/1.16.3/libexec/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00068e000, 0x2644e50, 0xc0007ca380, 0xc000124800)
	/Users/tdowney/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc0007ca000, 0x2644e50, 0xc0007ca380, 0xc000124800)
	/usr/local/Cellar/go/1.16.3/libexec/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00045ca00, 0x2647798, 0xc0007a6500)
	/usr/local/Cellar/go/1.16.3/libexec/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.16.3/libexec/src/net/http/server.go:3013 +0x39b
```

**Comment by angelachin** [comment]
## Acceptance

---

## Scenarios that did not pass acceptance

### Scenario: Happy path 

1. Created the app without providing lifecycle data and it defaults to kpack.

```
curl "http://localhost:9000/v3/apps" \
>   -X POST \
>   -d '{
>     "name": "my-app",
>     "relationships": {
>       "space": {
>         "data": {
>           "guid": "cf-workloads"
>         }
>       }
>     }
>   }'
{"guid":"954df01d-aeca-4aa4-8af3-0027388fc0bb","name":"my-app","state":"STOPPED","created_at":"2021-07-09T16:59:49Z","updated_at":"","lifecycle":{"type":"kpack","data":{"stack":"cflinuxfs3"}},"relationships":{"space":{"data":{"guid":"cf-workloads"}}},"links":{},"metadata":{"labels":{},"annotations":{}}}
```

2. Then took the provided guid and created a package

```
curl "http://localhost:9000/v3/packages" \
  -X POST \
  -d '{"type":"docker","relationships":{"app":{"data":{"guid":"954df01d-aeca-4aa4-8af3-0027388fc0bb"}}},"data":{"image":"registry/your-image:latest","username":"dockerusername","password":"dockerpassword"}}'
```

Saw that the package is created in the same namespace as the App. However, we saw that there is an error logged in the shim that says `error fecthing the created package: %!s(<nil>)`. This is unexpected behavior, although it does not seem to impact the shim running. We should fix the error.

### Scenario: Updating an App that does exist
1. Updated an App that had no buildpacks to use java and python
```
curl "http://localhost:9000/v3/apps/954df01d-aeca-4aa4-8af3-0027388fc0bb" \
  -X PUT \
  -d '{"name":"my-app","lifecycle":{"type":"kpack","data":{"buildpacks":["java_buildpack","python"],"stack":"cflinuxfs3"}}}'
```

Saw the following error in the shim:
```
error updating App object: App.apps.cloudfoundry.org "954df01d-aeca-4aa4-8af3-0027388fc0bb" is invalid: spec.lifecycle.data.buildpacks: Required value
```

We also tried updating an app that had a single buildpack and saw the same error. This is unexpected behavior.

---

## Scenarios that passed acceptance

### Scenario: Creating Package before the App

1. Created a Package

```
$ curl "http://localhost:9000/v3/packages"   -X POST   -d '{"type":"docker","relationships":{"app":{"data":{"guid":"9f924342-472a-43a1-9db9-54beba5401e2"}}},"data":{"image":"registry/your-image:latest","username":"dockerusername","password":"dockerpassword"}}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9000 (#0)
> POST /v3/packages HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 200
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 200 out of 200 bytes
< HTTP/1.1 422 Unprocessable Entity
< Date: Fri, 09 Jul 2021 16:57:08 GMT
< Content-Length: 46
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
Failed to create package as App does not exist* Closing connection 0
```

### Scenario: Updating an App that doesn't exist
Updated an App with a guid that doesn't exist
curl "http://localhost:9000/v3/apps/9f924342-472a-43a1-9db9-54beba5401e2" \
  -X PUT \
  -d '{"name":"my-app","lifecycle":{"type":"kpack","data":{"buildpacks":["java_buildpack","ruby"],"stack":"cflinuxfs3"}}}'
Got back the following error:
```
error updating App object: App.apps.cloudfoundry.org "954df01d-aeca-4aa4-8af3-0027388fc0bb" is invalid: spec.lifecycle.data.buildpacks: Required value
no matched apps for guid: 9f924342-472a-43a1-9db9-54beba5401e2
```

Other than the error trying to update which should be addressed when fixing the *Scenario: Updating an App that does exist* this looks good.

**Comment by heycait** [comment]
NOTES:

- When creating a package via the API, the guid is not returned in the response.
